### ISSUE TITLE
Text Spacing feature does not apply spacing following paragraphs

### ISSUE THREAD

**Issue by douga11y** [ThePacielloGroup/ARC-Toolkit#31]
**Describe the bug**

SC 1.4.12 including the following style property:

> Spacing following paragraphs to at least 2 times the font size;

For web-based content, it's recommended that this be tested using the following CSS:

```css
p {
    margin-bottom: 2em !important;
}
```

Currently, the ARC Toolkit feature for adjusting text spacing seems to apply the other 3 properties from this SC, but not spacing following paragraphs.

**To Reproduce**

1. In ARC Toolkit, go to 'Highlight'
2. Select the option to 'Check Text Spacing'
3. Inspect the page styles and/or visually check the style differences on the page.
4. The following CSS is injected, which does not include paragraph spacing.

```css
body.arcTextSpacingHelper * {
  line-height: 1.5 !important;
  letter-spacing: 0.12em !important;
  word-spacing: 0.16em !important;
}
```

**Expected behavior**

The Text Spacing feature in ARC Toolkit applies all of the style properties that are specifically called out in SC 1.4.12 to the best of its ability.

Note that I say 'to the best of its ability' here because there is an assumption that authors are using HTML `<p>` elements to define paragraphs of text. This is not always the case and it is not uncommon for authors to use generic `<div>` elements or similar for blocks of text. However, applying these properties to generic elements like `<div>` would be unwise, and not a good representation of the intent of this criteria.

**Version information**

- Browser and version: Google Chrome version 109.0.5414.119
- ARC Toolkit version: 5.4.2
